#!/bin/bash
cd travis_qmake_gcc_cpp98

# Remove all warnings
sed 's/^QMAKE_CXXFLAGS/# QMAKE_CXXFLAGS/' travis_qmake_gcc_cpp98.pro

# Can pick either
# i686-w64-mingw32.static-qmake-qt4
i686-w64-mingw32.static-qmake-qt5

make

cd ..

if [ ! -f ./travis_qmake_gcc_cpp98/release/travis_qmake_gcc_cpp98.exe ]
then
  echo "Error: Windows executable has not been created"
  exit 1
fi

